### PR TITLE
299 refactoring removing range cluster 03

### PR DESCRIPTION
**Pull request by alexander-schulze**
This pull request removes range constraints from ten object properties in ebucoreplus ontology. 
#### Changes
- Removed the range "CurrencyCode" from the property "hasArtefactPriceCurrency".
- Removed the range "Location" from the property "hasArtefactRelatedLocation".
- Removed the range "PhysicalResource" from the property "hasArtefactRelatedPhysicalResource".
- Removed the range "Agent" from the property "hasArtefactRetailer".
- Removed the range "Agent" from the property "hasArtefactSupplier".
- Removed the range "Article" from the property "hasArticle".
- Removed the range "Artefact" from the property "hasAssociatedArtefact".
- Removed the range "Relation" from the property "hasAssociatedRelation".
- Removed the range "skos:Concept" from the property "hasAudienceScoreRecordingTechnique".
- Removed the range "AudioDescription" from the property "hasAudioDescription".
#### Reviewer
@aro-max 
@JuergenGrupp

### CODE REVIEW

**Review by aro-max — APPROVED** [review]
Perfect, thank you Alex, this one was easy to check :-)

**Comment by alexander-schulze** [comment]
@JuergenGrupp 
Can you please review it?

**Comment by alexander-schulze** [comment]
Hey @JuergenGrupp,
Can you please review it?

**Comment by JuergenGrupp** [comment]
Well done, thank you @alexander-schulze !

**Review by JuergenGrupp — COMMENTED** [review]
Everything's fine, I already merged the result.

**Pull request merged**
