### PR TITLE
299 refactoring has property cluster 05

### PR DESCRIPTION
**Pull request by alexander-schulze**
In this pull request, I have standardized the naming of ten object properties by adding a 'has' prefix.
   
- `loggsPublicationEvent` to `hasLoggsPublicationEvent`
- `measureValueUnit` to `hasMeasureValueUnit`
- `objectType` to `hasObjectType`
- `previousRelatedProductionJob` to `hasPreviousRelatedProductionJob`
- `provenance` to `hasProvenance`
- `publicationPlanStatus` to `hasPublicationPlanStatus`
- `publicationScheduleDate` to `hasPublicationScheduleDate`
- `relationLink` to `hasRelationLink`
- `resourceOffset` to `hasResourceOffset`
- `rightsTerritoryExcludes` to `hasRightsTerritoryExcludes`

**Reviewers**
- @JuergenGrupp 
- @aro-max

### CODE REVIEW

**Comment by JuergenGrupp** [comment]
`loggsPublicationEvent` is misspelled. It should read `logsPublicationEvent`. This reveals "logs" as being the active form of "to log" and therefore the property does not need to be corrected in naming. It only needs to be corrected in spelling.

**Review by aro-max — APPROVED** [review]
thank you

**Comment by alexander-schulze** [comment]
@JuergenGrupp Can you please review the changes?

**Review by JuergenGrupp — CHANGES_REQUESTED** [review]
Looks good, except for one change: the property "hasLogsPublicationEvent" needs to be renamed to "logsPublicationEvent", because the "has-Rule" does not apply to the verb "logs" which is the simple present for he/she/it of "to log".

**Pull request merged**
