### PR TITLE
299 refactoring has property cluster 01

### PR DESCRIPTION
**Pull request by alexander-schulze**
In this pull request, I have standardized the naming of ten object properties by adding a 'has' prefix.
   
- `artefactDateOfPurchase` to `hasArtefactDateOfPurchase`
- `date` to `hasDate`
- `artefactDateOfSell` to `hasArtefactDateOfSell`
- `assetValueCurrency` to `hasAssetValueCurrency`
- `auditReportDate` to `hasAuditReportDate`
- `awardDate` to `hasAwardDate`
- `consumptionDeviceManufacturer` to `hasConsumptionDeviceManufacturer`
- `consumptionEventResumePoint` to `hasConsumptionEventResumePoint`
- `consumptionLicenceLink` to `hasConsumptionLicenceLink`
- `contractLink` to `hasContractLink`

**Reviewers**
- @JuergenGrupp 
- @aro-max

### CODE REVIEW

**Review by JuergenGrupp — CHANGES_REQUESTED** [review]
Looks good to me! 
Just a very little correction requested: 
"hasArtefactDateOfSell" is better named "hasArtefactDateOfSale", because "sale", not "sell", is the antonym of "purchase" (used in "hasArtefactDateOfPurchase").

**Review by JuergenGrupp — APPROVED** [review]
Some minor errors and inconsistencies on the wording will be dealt with in another issue.

**Review by aro-max — COMMENTED** [review]
Thank you.  "hasArtefactDateOfSale" would be more grammatically correct than "hasArtefactDateOfSell".  Do you agree ?

**Review by aro-max — APPROVED** [review]

**Comment by alexander-schulze** [comment]
@JuergenGrupp @aro-max, I have resolved the conflicts. Can you please merge the branches now?

**Pull request merged**
