### PR TITLE
299 refactoring removing range cluster 02

### PR DESCRIPTION
**Pull request by alexander-schulze**
This pull request removes range constraints from ten object properties in ebucoreplus ontology. 
#### Changes
- Removed the range "AncillaryData" from the property "hasAncillaryData".
- Removed the range "AnimalBreedCode" from the property "hasAnimalBreedCode".
- Removed the range "AnimalColourCode" from the property "hasAnimalColourCode".
- Removed the range "Agent" from the property "hasAnimalGroom".
- Removed the range "Involvement" from the property "hasAnimalRole".
- Removed the range "Agent" from the property "hasAnnotationAgent".
- Removed the range "time:Instance" from the property "hasAnnotationCurationDateTime".
- Removed the range "owl:Thing" from the property "hasAnnotationTarget".
- Removed the range "Agent" from the property "hasArtefactBuyer".
- Removed the range "Agent" from the property "hasArtefactOwner".
#### Reviewer
@aro-max 
@JuergenGrupp

### CODE REVIEW

**Review by JuergenGrupp — APPROVED** [review]
Thank you, @alexander-schulze !
Looks good to me.
A cosmetic problem: the first commit shows more than 150 lines changed, because of an additional or missing blank in those lines. This made it a little more difficult to review the changes. Is there a systematic reason for that? Can we avoid it in the future to speed up the review process?

**Comment by alexander-schulze** [comment]
Hey @JuergenGrupp,
The issue with 150 lines changed due to blanks happening automatically when I removed the range and saved the file. I'll investigate this in my next commit to prevent it.

**Comment by alexander-schulze** [comment]
Hey @aro-max,
Can you please review it?

**Comment by JuergenGrupp** [comment]
this is a gentle nudge to @aro-max to review this, please!

**Review by aro-max — APPROVED** [review]

**Pull request merged**
