### PR TITLE
267 subclasses of editorial work for extra content alex

### PR DESCRIPTION
**Pull request by alexander-schulze**
Thanks Jürgen for your final translations. Like aligned, the update is ready for review and to be merged into the main branch.

### CODE REVIEW

**Comment by alexander-schulze** [comment]
Removed Interview Class like agreed.

**Comment by JuergenGrupp** [comment]
I would like to have the dcterms:description annotations to the classes Trailer and MakingOf re-inserted, as we had decided to keep them, even if we want to add skos:defintions to all entitities in the long run and thereby replace the dcterms:definition. The reason for that was to understand the earlier semantical intention while being in the process of adding the skos:definitions. Once we have added skos:definitions to all entities, we can then probably remove the dcterms:descripitions without losing valuable information.

**Comment by alexander-schulze** [comment]
re-inserted dcterms:description annotations to the classes Trailer and MakingOf.

**Comment by alexander-schulze** [comment]
Noticed that the dcterm:description was removed for other subclasses of Editorial Extra as well. Should these be recovered as well?

**Comment by JuergenGrupp** [comment]
Yes, please. 
dcterms:description should only be removed, when we have completed the task to add skos:definitions to all classes.

**Comment by alexander-schulze** [comment]
Fixed wrong rdfs:prefLabel by replacing through skos:prefLabel.

**Review by JuergenGrupp — APPROVED** [review]
Thank you, looks good to me!

**Pull request merged**
