### PR TITLE
remove audioTrackNumber and change to nonNegativeInteger for numberOf…

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**
…*Tracks

issue #342

### CODE REVIEW

**Review by JuergenGrupp — APPROVED** [review]
Thank you, @MarcAntoine-Arnaud !
No need for duplicate property. No negative number of tracks possible.
@alexander-schulze : Any objections?

**Comment by JuergenGrupp** [comment]
EBU EditorialCommittee:
Please re-analyse: audioTrackNumber (in the sense of "index") is NOT the same as hasNumberOfAudioTracks (in the sense of "count").

**Comment by alexander-schulze** [comment]
Hey @MarcAntoine-Arnaud, @JuergenGrupp 
Currently, both **`audioTrackNumber`** and **`numberOfVideoTracks`** have similar comments in the ontology, but their actual meanings are different:

- **`audioTrackNumber`** refers to **a specific audio track** in a media file (e.g., track 1 for English audio in a multi-language video).
- **`numberOfVideoTracks`** represents **the total number of video tracks** available (e.g., two video streams for different camera angles).

If we use these properties for their distinct meanings, we should keep both and update the comments in the ontology to reflect their unique purposes.

However, if the goal is to represent only the total number of tracks, not individual audio tracks, we can remove `audioTrackNumber` and keep `numberOfVideoTracks`, which would then represent the total count of both audio and video tracks.

**Comment by JuergenGrupp** [comment]
Comment by the Editorial Committee:

- we need a field for the index of the audio track
- we need a field for the total count of the audio tracks
- we should rename those two to the intended meaning

Conclusion: we will decline the pull request, but improve the naming of the properties

**Comment by JuergenGrupp** [comment]
This pull request is declined in favor of https://github.com/ebu/ebucoreplus/issues/369.

**Pull request closed without merging**
