### PR TITLE
adding definitions and examples to classes related to production and …

### PR DESCRIPTION
**Pull request by JuergenGrupp**
…role related classes

### CODE REVIEW

**Review by aro-max — COMMENTED** [review]
It is clear. I just have a question related to the definition of a contract. Please see my remark.

**Review by aro-max — APPROVED** [review]
Thank you. It is clear and precise. I found the answer to my previous question. 
Excellent work.

**Comment by JuergenGrupp** [comment]
The definition of Contract was put into an annotation of type skos:example. Typical editing trap in Protégé. I corrected it from skos:example to skos:definition.

**Comment by aro-max** [comment]
merged with main via an intermediate branch : merge-skos-lab-desc

**Pull request closed without merging**
