### PR TITLE
299 refactoring renaming property cluster 01

### PR DESCRIPTION
**Pull request by alexander-schulze**
This pull request includes the renaming of ten object properties.

- `appliesOutOf` to `hasTerritoryExcludes`
- `appliesTo` to `hasTerritoryIncludes`
- `applyTo` to `hasTerritoryIncludes`
- `clonedTo` to `hasClone`
- `isClonedFrom` to `isCloneOf`
- `dubbedTo` to `hasDub`
- `isDubbedFrom` to `isDubOf`
- `isCoveredBy` to `hasRights`
- `isAgent` to `hasRelatedAgent`
- `isAnimalGroom` to `hasAnimalGroom`

**Reviewers**
- @JuergenGrupp 
- @aro-max

### CODE REVIEW

**Comment by JuergenGrupp** [comment]
I have 3 improvements to this pull request:

1) I think I have spotted an error in our renaming plan of `applyTo`:
`applyTo` is currently only used here: Rights `applyTo` Asset. 
The wording seemed strange at first, because of the plural "apply" instead of "applies". That is why we proposed this change to `hasTerritoryIncludes`. But the meaning would change with `hasTerritoryInclude`and the grammar of `applyTo` is fully correct and expresses exactly what our intention is.
My conclusion: stick with `applyTo` and do not rename it.

2) There is another class to use `applyTo` with: `PublicationEvent`.
My conclusion: add the following restriction to the ontology: "Rights `applyTo` PublicationEvent. 

3) This opens up the opportunity to make "applyTo" and "isCoveredBy" inverse properties.
My conclusion: add the rule `applyTo` `isInverseOf` `isCoveredBy`

Please comment!

**Comment by alexander-schulze** [comment]
Yes @JuergenGrupp, I agree. 
@aro-max do you agree with these changes so I can proceed with making the updates?

**Comment by alexander-schulze** [comment]
Yes @JuergenGrupp, I agree. 
@aro-max  do you agree with these changes so I can proceed with making the updates?

**Review by aro-max — APPROVED** [review]

**Comment by alexander-schulze** [comment]
Here are the latest changes made:

1. Reinitialized the `applyTo` object property instead of renaming it to `hasTerritoryIncludes`.
2. Removed the `Rights hasTerritoryIncludes Asset` restriction and replaced it with the `Rights applyTo Asset` restriction.
3. Added a new restriction: `Rights applyTo PublicationEvent`.
4. Added `applyTo` object property as the inverse of the `isCoveredBy` object property, which is renamed to `hasRights`.

**Comment by alexander-schulze** [comment]
@JuergenGrupp, can you please review the latest changes?

**Review by JuergenGrupp — CHANGES_REQUESTED** [review]
Looking at the diff, I found inconsistencies that should to be cleared for approval:
Property `hasRelatedAgent`:
1) The new declaration seems to have unintentionally mixed in property values from the intentionally deleted property `isAgent`:   `rdfs:label` and `dcterms:description` are now present with 6 values each, while they should only have 3 because of the 3 languages that we support. The mixed in values should be removed and only the original ones should be left.
2) Also the `owl:IrreflexiveProperty` comes from `isAgent` and should be removed.

**Comment by alexander-schulze** [comment]
Cleaned up mixed-in property values for rdfs:label and dcterms:description from hasRelatedAgent, ensuring only 3 values for supported languages, and removed owl:IrreflexiveProperty from hasRelatedAgent.

**Review by JuergenGrupp — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
